export const renderStorageErrorView = (message, actions) => {
    const root = document.createElement("section");
    const header = document.createElement("section");
    header.className = "hero";
    const heading = document.createElement("h1");
    heading.textContent = "Browser storage unavailable";
    const description = document.createElement("p");
    description.textContent = "OpenMCAT could not safely access its private database in your web browser. Existing OpenMCAT data has not been deleted.";
    header.append(heading, description);
    const card = document.createElement("section");
    card.className = "card card-pad empty-state";
    const detail = document.createElement("p");
    detail.className = "danger-note";
    detail.textContent = message;
    const guidance = document.createElement("p");
    guidance.className = "muted-note";
    guidance.textContent = "Close other OpenMCAT tabs, confirm that this web browser allows site storage, and then try again.";
    const controls = document.createElement("div");
    controls.className = "button-row dashboard-empty-actions";
    const retry = document.createElement("button");
    retry.type = "button";
    retry.className = "btn btn-primary";
    retry.textContent = "Try again";
    retry.addEventListener("click", () => actions.initApp());
    const reload = document.createElement("button");
    reload.type = "button";
    reload.className = "btn btn-secondary";
    reload.textContent = "Reload OpenMCAT";
    reload.addEventListener("click", () => location.reload());
    controls.append(retry, reload);
    card.append(detail, guidance, controls);
    root.append(header, card);
    return root;
};
